name: Build and Deploy Jekyll

on:
  push:
    branches:
      - one_page

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Bundler
        run: gem install bundler

      - name: Install Jekyll dependencies
        run: bundle install

      - name: Build Jekyll and Initialize _site as Git repository
        run: |
          bundle exec jekyll build --destination _site
          cd _site
          git init  # Initialize _site as a Git repository
          
  report-build-status:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Report Build Status
        run: |
          # Add your code to report build status here
          # This step can include notifications or other actions

  deploy:
    needs: report-build-status
    runs-on: ubuntu-latest
    steps:
    - name: Prepare for Deployment
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Add all files and commit changes from the _site directory
        git -C _site add --all
        git -C _site commit -m "GitHub Pages deploy"
        
        # Push changes to the gh-pages branch
        git -C _site push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/DanielGroneberg/DanielGroneberg.github.io" master:gh-pages
