name: Build and Deploy Jekyll

on:
  push:
    branches:
      - one_page

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Bundler
        run: gem install bundler

      - name: Install Jekyll dependencies
        run: bundle install

      - name: Build Jekyll and Initialize _site as Git repository
        run: |
          bundle exec jekyll build --destination _site
          cd _site
          git init

      - name: List contents of _site directory
        run: ls -l _site

  report-build-status:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Report Build Status
        run: |
          # Add your code to report build status here
          # This step can include notifications or other actions

  deploy:
    needs: report-build-status
    runs-on: ubuntu-latest
    steps:
      - name: Prepare for Deployment
        working-directory: ./_site  # Specify the working directory
        run: |
          git init
  
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
  
          # Add all files and commit changes
          git add --all
          git commit -m "GitHub Pages deploy"
  
          # Push changes to the gh-pages branch
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/DanielGroneberg/DanielGroneberg.github.io.git" master:gh-pages
